name: Build openssl.wasm  

on:
  push:
    branches : [ main ]
    tags:
      - "v*.*.*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag openssl-wasm:latest
    - name: Build openssl.wasm
      run: docker run --name openssl-wasm-container openssl-wasm
    - name: Copy openssl.wasm from container
      run: docker cp openssl-wasm-container:/build/openssl.wasm .
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: openssl.wasm
